language: cpp
os:
  - linux
dist: bionic
sudo: required
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - clang-7
      - llvm-7-dev
script:
  - ./configure && make && make check && sudo make install
